package com.agenticproficient.urlshortner.agentic.model;

public enum WorkflowEventType {
	APPROVAL_GRANTED,
	APPROVAL_REJECTED,
	APPROVAL_REQUIRED,
	FALLBACK_APPLIED,
	POLICY_DENIED,
	RETRY_SCHEDULED,
	ROLLBACK_TRIGGERED,
	RUN_COMPLETED,
	RUN_CREATED,
	RUN_SAFE_STOPPED,
	STEP_COMPLETED,
	STEP_STARTED
}
